# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'geocoding_api' %>
  password: <%= ENV['POSTGRES_PASS'] || '' %>
  database: <%= ENV['POSTGRES_DB'] || 'geocoding_api_dev' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'geocoding_api_test' %>

production:
  <<: *default
